### ISSUE TITLE
unknown tag error when previewing locally with jekyll

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/styles#195] opened 2017-12-11 17:54 UTC
I'm following the steps [here](http://swcarpentry.github.io/lesson-example/setup.html) to create a new lesson and run into a problem when I try to preview the page locally (step 13 of the instructions). From the error message (shown below), it appears that the tag name `link` is not recognized by Jekyll. Has anyone else had this issue? How do we fix it?

~~~
Erins-MacBook-Air-2:maintainer-onboarding ebecker$ make serve
jekyll serve
Configuration file: /Users/ebecker/Box Sync/Carpentry_repos/carpentry-lessons/maintainer-onboarding/_config.yml
            Source: /Users/ebecker/Box Sync/Carpentry_repos/carpentry-lessons/maintainer-onboarding
       Destination: /Users/ebecker/Box Sync/Carpentry_repos/carpentry-lessons/maintainer-onboarding/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 30): Unknown tag 'link' in _includes/navbar.html, included in _layouts/base.html
jekyll 3.1.5 | Error:  Liquid syntax error (line 30): Unknown tag 'link'
make: *** [serve] Error 1
~~~

**Comment by rgaiacs** [comment] 2017-12-12 13:51
Please update your Jekyll installation to 3.2 or higher. `link` was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so `link` is available to use in our current workflow.

I'm closing this as not a bug and as duplicated of https://github.com/swcarpentry/lesson-example/issues/143. Thanks for the report!

If you have time, a pull request to http://swcarpentry.github.io/lesson-example/setup.html stating that you need Jekyll 3.2 or higher would be great.

**Closed by rgaiacs** 2017-12-12 13:51 UTC

**Comment by ErinBecker** [comment] 2017-12-12 16:14
Thanks @rgaiacs. That's very useful information. I will update my Jekyll and put in the PR to lesson-example.
