### ISSUE TITLE
Prev/Next arrows do not appear properly on some browsers

### ISSUE THREAD

**Issue by colinbrislawn** [swcarpentry/styles#160] opened 2017-07-28 17:38 UTC
On Internet Explorer, these arrows do not appear:
![image](https://user-images.githubusercontent.com/10355152/28729235-a148a750-7380-11e7-9d19-2b4027b2367e.png)

This was confusing for new windows users!

These arrows were added in #78, and it looks like some more testing is needed.

**Comment by gdevenyi** [comment] 2017-07-28 19:24
What version of IE?

**Comment by colinbrislawn** [comment] 2017-07-28 20:25
IE 11.0.9600.18698 

I'm in front of my mac now, so this list may be incomplete. I have not tested this on edge.

**Comment by rgaiacs** [comment] 2017-07-29 13:14
@colinbrislawn Thanks for the issue. I can't reproduce your error, see the screenshot. I'm closing this issue since there isn't much that we could do if one minor release of IE has a bug. Feel free to reopen this issue if you know more users that are being effect by this issue.

# Screenshots

Note: Screenshots took using https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.

Internet Explorer 11.0.9600.17420

![virtualbox_ie11 - win7_29_07_2017_14_03_27](https://user-images.githubusercontent.com/1506457/28745041-2f958f00-7467-11e7-99c1-946f0296a727.png)

http://swcarpentry.github.io/shell-novice/

![virtualbox_ie11 - win7_29_07_2017_14_09_26](https://user-images.githubusercontent.com/1506457/28745054-a0513226-7467-11e7-8590-a945ecac7373.png)

http://swcarpentry.github.io/git-novice/

![virtualbox_ie11 - win7_29_07_2017_14_06_04](https://user-images.githubusercontent.com/1506457/28745042-31dd4334-7467-11e7-8edb-d6b7c0412827.png)

**Closed by rgaiacs** 2017-07-29 13:14 UTC

**Comment by colinbrislawn** [comment] 2017-07-29 14:46
Thanks for helping me review this. I'm back in front of my PC, running fully patched Windows 10. Looks like the website renders great on IE and Edge.

Let me see what IE on Windows 7 looks like...

**Comment by colinbrislawn** [comment] 2017-07-29 16:16
So old IE 9 still renders these arrows.
![ie9-capture](https://user-images.githubusercontent.com/10355152/28746290-188cc31a-743e-11e7-8e28-5d0dc21f52f8.PNG)

I'm sorry I wasn't much help here. Let's close until we know more.
