### ISSUE TITLE
Error in current master Could not find document 'index.md' in tag 'link'

### ISSUE THREAD

**Issue by henrykironde** [swcarpentry/styles#235] opened 2018-04-25 16:02 UTC
Liquid Exception: Could not find document 'index.md' in tag 'link'. Make sure the document exists and the path is correct. in /_layouts/page.html
jekyll 3.7.0 | Error:  Could not find document 'index.md' in tag 'link'.

Make sure the document exists and the path is correct.

**Comment by rgaiacs** [comment] 2018-04-25 16:12
You should not build this repository!

As mentioned in http://swcarpentry.github.io/lesson-example/02-tooling/index.html,

> The lesson template does not include _config.yml, since each lesson will change some of its value, which would result in merge collisions each time the lesson was updated from the template. Instead, the template contains a script called bin/lesson_initialize.py which should be run once to create an initial _config.yml file (and a few other files as well). The author should then edit the values in the top half of the file.

I'm closing this since it is not a bug.

**Closed by rgaiacs** 2018-04-25 16:12 UTC
